# Generated by Django 2.2.5 on 2019-09-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('introduce', models.TextField(null=True)),
                ('identity', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.TeacherIdentity')),
                ('teacher_icon', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Icon')),
                ('teacher_sex', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('introduce', models.TextField(null=True)),
                ('notice', models.TextField(null=True)),
                ('course_icon', models.CharField(max_length=255)),
                ('integral', models.IntegerField(default=0, null=True)),
                ('publist_tiem', models.DateTimeField(auto_now_add=True)),
                ('classify_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Classify')),
                ('difficulty_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Difficulty')),
                ('pre_course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('teacher_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='classify',
            name='direction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Direction'),
        ),
    ]
