# Generated by Django 2.2.5 on 2019-09-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courseware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('courseware_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCourseware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('qc_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iswatch', models.IntegerField(default=0)),
                ('courseware_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseware.Courseware')),
            ],
        ),
    ]
