# Generated by Django 2.2.5 on 2019-09-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseDetails', '0001_initial'),
        ('user', '0001_initial'),
        ('courseware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseware',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='questioncourseware',
            name='courseware_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseware.Courseware'),
        ),
        migrations.AddField(
            model_name='questioncourseware',
            name='question_courseware_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseware.QuestionCourseware'),
        ),
        migrations.AddField(
            model_name='questioncourseware',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='courseware',
            name='chapter_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseDetails.Chapter'),
        ),
    ]
