# Generated by Django 2.2.5 on 2019-09-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190917_1951'),
        ('courseware', '0002_auto_20190917_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseware',
            old_name='chapter_id',
            new_name='chapter',
        ),
        migrations.RemoveField(
            model_name='questioncourseware',
            name='courseware_id',
        ),
        migrations.RemoveField(
            model_name='questioncourseware',
            name='question_courseware_id',
        ),
        migrations.RemoveField(
            model_name='questioncourseware',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usercourseware',
            name='courseware_id',
        ),
        migrations.RemoveField(
            model_name='usercourseware',
            name='user_id',
        ),
        migrations.AddField(
            model_name='questioncourseware',
            name='courseware',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseware.Courseware'),
        ),
        migrations.AddField(
            model_name='questioncourseware',
            name='question_courseware',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseware.QuestionCourseware'),
        ),
        migrations.AddField(
            model_name='questioncourseware',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='usercourseware',
            name='courseware',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseware.Courseware'),
        ),
        migrations.AddField(
            model_name='usercourseware',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
