# Generated by Django 2.2.5 on 2019-09-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='course_id',
            new_name='course',
        ),
    ]
