# Generated by Django 2.2.5 on 2019-09-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190917_1951'),
        ('note', '0002_note_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user_id',
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
